site_name: Virtual Reading Room
site_url: https://shellyyblack.github.io/vrr/
nav:
    - Home: 'index.md'
    - 'User Guide':
        - Overview: 'user-guide.md'
        - 1. Creating an account: 'user-guide/creating-account.md'
        - 2. Authenticating: 'user-guide/authenticating.md'
        - 3. Connecting: 'user-guide/connecting.md' 
    - Troubleshooting: 'troubleshooting.md'
theme:
    name: mkdocs
    custom_dir: custom_theme/
extra_css: [extra.css]
docs_dir: 'src'
site_dir: 'docs'